### ISSUE TITLE
Google.Cloud.Kms.V1 please upgrade the version(get_isknownpattern error)

### ISSUE THREAD

**Issue by chrise1967** [GoogleCloudPlatform/google-cloud-dotnet-powerpack#18]
I have recently tried to use Google.Cloud.SecretManager.V1 with the dataprotection and got the error below.but this uses version 2.0.0 for Kms.V1 and I am getting the error 

an exception of type 'system.typeloadexception' occurred in quidvis-presentation.dll but was not handled in user 'method 'get_isknownpattern' in type 'google.cloud.kms.v1.cryptokeyname' from assembly 'google.cloud.kms.v1 version1.0

This is because Google.Cloud.SecretManager.V1 uses the new version of Google.Cloud.Kms.V1 which is 2.0.0.

Kind Regards
Chris

**Comment by jskeet** [comment]
Thanks for spotting this - will try to get to it this week.

**Comment by ikhramts** [comment]
Same here. 

I've just upgraded to ASP.NET Core 3.1. Trying to use `Google.Cloud.AspNetCore.DataProtection.Kms` v1.0.0-alpha2 with `Google.Cloud.Diagnostics.AspNetCore` v4.0.0, which are the latest versions for both. The two seem to depend on incompatible versions of `Google.Api.Gax.Grpc`, which causes the same error.

**Comment by jskeet** [comment]
Yes, it's still the same issue - I haven't managed to get round to a new release yet, but I'll try to do it soon. (It's relatively low in our list of priorities compared with other work, but we'll try to get to it.)

**Comment by jskeet** [comment]
I've now released 1.0.0-alpha03 of all packages.
