### ISSUE TITLE
Still not resolved 

### ISSUE THREAD

**Issue by rbokhari** [GoogleCloudPlatform/google-cloud-dotnet-powerpack#20]
Hello, I don't want to try that google libraries to try in asp.net solution, there should a asp.net solution with itself. 

Any idea how to do that ?

**Comment by jskeet** [comment]
I'm afraid we don't know what you mean:

- We don't know what is "still not resolved"
- We don't know what you mean by "I don't want to try that google libraries to try in asp.net solution"
- We don't know what package you're trying to use
- We don't know what issue you're facing with it

Please provide more information or we won't be able to help you.

**Comment by jskeet** [comment]
Closing due to lack of further information.
